### ISSUE TITLE
gem is not published?

### ISSUE THREAD

**Issue by dreamcat4** [hihouhou/huginn_twitter_publishv2_agent#1]
Hi,
Trying to get this to work with my orchestrator here (which is crane). And I don't actually have any such `.env` file to begin with.

instead added the env var into `docker run -e` as an environment variable

```yaml
  huginn:
    image: huginn/huginn
    depends_on:
      - huginn.id.postgres.v13
    restart: always
    env:
      - RAILS_ENV=production
      - ADDITIONAL_GEMS=huginn_twitter_publishv2_agent
      - MORE_ENV_VARS=....
```

However unfortunately this does not work here, since your gem isn't published on rubygems?

```sh
No mail for id
docker logs -f huginn
You are replacing the current local value of without, which is currently "test:development"
Fetching gem metadata from https://rubygems.org/......
Could not find gem 'huginn_twitter_publishv2_agent' in rubygems repository
https://rubygems.org/ or installed locally.
You are replacing the current local value of without, which is currently "test:development"
Fetching gem metadata from https://rubygems.org/......
Could not find gem 'huginn_twitter_publishv2_agent' in rubygems repository
https://rubygems.org/ or installed locally.
You are replacing the current local value of without, which is currently "test:development"
Fetching gem metadata from https://rubygems.org/......
Could not find gem 'huginn_twitter_publishv2_agent' in rubygems repository
https://rubygems.org/ or installed locally.
```

So I was just wondering how to tackle this. And to be clear: no missing `bundle` cmdline step was performed either. Which i suppose would also be another missing thing (when it's not found via rubgygems).
